server:  port: 8001  eureka:  client:    service-url:      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  instance:    instance-id: microservices-dept8001    prefer-ip-address: true
spring:   application:    name: microservices-dept #服务名
  datasource: #数据库连接池    username: root    password: root    # 使用druid连接池    type: com.alibaba.druid.pool.DruidDataSource
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
  
mybatis-plus:   mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.charlie.api  configuration:    map-underscore-to-camel-case: true
  global-config:    db-config:      table-underline: trueinfo:  app.name: charlie.microservices  company.name: www.charlie5115.com  build.artifactId: $project.artifactId$  build.version: $project.version$