server:
  port: 9527
  
spring:
  application:
    name: microservices-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservices-getway9527
    prefer-ip-address: true

zuul:
  prefix: /charlie
  ignored-services: "*"  routes:    mydept.serviceId: microservices-dept
    mydept.path: /mydept/**

info:
  app.name: charlie.microservices
  company.name: www.charlie5115.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$