server:
  port: 9001
  
spring:  application:    name: microservices-dept-feign-9001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservices-dept801
    prefer-ip-address: true

info:
  app.name: charlie.microservices
  company.name: www.charlie5115.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$